[package]
name = "multiple_binaries"
version = "0.1.0"
edition = "2024"

[dependencies]


[[bin]]
name = "server_end"
path = "src/bin/server.rs"

[[bin]]
name = "client_end"
path = "src/bin/client.rs"
